---
extends: default

rules:
  # Allow longer lines for descriptive text
  line-length:
    max: 120
    level: warning

  # Home Assistant uses 2-space indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow duplicate keys in some cases (Home Assistant conventions)
  key-duplicates:
    level: error

  # Be flexible with comments
  comments:
    min-spaces-from-content: 1
    level: warning

  # Allow empty values (common in HA config)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Document start (---) is optional
  document-start:
    level: warning

  # Trailing spaces should be warnings, not errors
  trailing-spaces:
    level: warning

  # Truthy values (yes/no vs true/false)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false
    level: warning
