# Pre-built images from GitHub Container Registry
# Built via GitHub Actions on version tags
# {arch} replaced by HA with: amd64, aarch64, or armv7
image: "ghcr.io/owine/claude-terminal-prowine-{arch}"

labels:
  org.opencontainers.image.title: "Claude Terminal Prowine"
  org.opencontainers.image.description: "Enhanced terminal interface for Claude Code CLI"
  org.opencontainers.image.source: "https://github.com/owine/claude-terminal-home-assistant"
  org.opencontainers.image.licenses: "MIT"