# Build configuration for GitHub Actions builder
# Architecture-specific base images (managed by Renovate)
# renovate: datasource=docker depName=ghcr.io/home-assistant/aarch64-base versioning=loose
# renovate: datasource=docker depName=ghcr.io/home-assistant/amd64-base versioning=loose
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.23
  amd64: ghcr.io/home-assistant/amd64-base:3.23

# Pre-built images location (what users pull)
# Built via GitHub Actions, then pushed to ghcr.io
image: "ghcr.io/owine/claude-terminal-prowine-{arch}"

labels:
  org.opencontainers.image.title: "Claude Terminal Prowine"
  org.opencontainers.image.description: "Enhanced terminal interface for Claude Code CLI"
  org.opencontainers.image.source: "https://github.com/owine/claude-terminal-home-assistant"
  org.opencontainers.image.licenses: "MIT"